export const HISTORY_LIST_REQUEST = 'HISTORY_LIST_REQUEST'
export const HISTORY_LIST_SUCCESS = 'HISTORY_LIST_SUCCESS'
export const HISTORY_LIST_FAILED = 'HISTORY_LIST_FAILED'
export const HISTORY_LIST_RESET = 'HISTORY_LIST_RESET'

export const HISTORY_RATING_REQUEST = 'HISTORY_RATING_REQUEST'
export const HISTORY_RATING_SUCCESS = 'HISTORY_RATING_SUCCESS'
export const HISTORY_RATING_FAILED = 'HISTORY_RATING_FAILED'
export const HISTORY_RATING_RESET = 'HISTORY_RATING_RESET'