export const HISTORY_LIST_REQUEST = 'HISTORY_LIST_REQUEST'
export const HISTORY_LIST_SUCCESS = 'HISTORY_LIST_SUCCESS'
export const HISTORY_LIST_FAILED = 'HISTORY_LIST_FAILED'
export const HISTORY_LIST_RESET = 'HISTORY_LIST_RESET'